version: '3.8'
services:
  miniafl:
    build:
      context: ../..
      dockerfile: scripts/docker/Dockerfile.ubuntu22
    image: miniafl:ubuntu22
    shm_size: 1g
    volumes:
      - ../../testcases:/workspace/testcases
      - ../../MiniAFL:/workspace/MiniAFL
    tty: true
    stdin_open: true
